In [ ]:
# Install the streamlit and plotly packages
%pip3 install streamlit
%pip3 install plotly
%pip3 install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: streamlit in /Users/Grace/Library/Python/3.9/lib/python/site-packages (1.43.1)
Requirement already satisfied: cachetools<6,>=4.0 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from streamlit) (5.5.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from streamlit) (3.1.44)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from streamlit) (0.9.1)
Requirement already satisfied: packaging<25,>=20 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from streamlit) (24.2)
Requirement already satisfied: pandas<3,>=1.4.0 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from streamlit) (2.2.3)
Requirement already satisfied: toml<2,>=0.10.1 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from streamlit) (0.10.2)
Requirement already satisfied: altair<6,>=4.0 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from streamlit) (5.5.0)
Requirement already satisfied: click<9,>=7.0 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from streamlit) (8.1.8)
Requirement already satisfied: pillow<12,>=7.1.0 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from streamlit) (11.1.0)
Requirement already satisfied: pyarrow>=7.0 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from streamlit) (19.0.1)
Requirement already satisfied: tornado<7,>=6.0.3 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from streamlit) (6.4.2)
Requirement already satisfied: requests<3,>=2.27 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from streamlit) (2.32.3)
Requirement already satisfied: tenacity<10,>=8.1.0 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from streamlit) (9.0.0)
Requirement already satisfied: numpy<3,>=1.23 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from streamlit) (2.0.2)
Requirement already satisfied: protobuf<6,>=3.20 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from streamlit) (5.29.3)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from streamlit) (4.12.2)
Requirement already satisfied: blinker<2,>=1.0.0 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from streamlit) (1.9.0)
Requirement already satisfied: jinja2 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from altair<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: narwhals>=1.14.2 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from altair<6,>=4.0->streamlit) (1.30.0)
Requirement already satisfied: jsonschema>=3.0 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: referencing>=0.28.4 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.23.1)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2024.10.1)
Requirement already satisfied: attrs>=22.2.0 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (25.1.0)
Requirement already satisfied: pytz>=2020.1 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from pandas<3,>=1.4.0->streamlit) (2025.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from pandas<3,>=1.4.0->streamlit) (2025.1)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)
Requirement already satisfied: six>=1.5 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from requests<3,>=2.27->streamlit) (2025.1.31)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from requests<3,>=2.27->streamlit) (2.3.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from requests<3,>=2.27->streamlit) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from requests<3,>=2.27->streamlit) (3.10)
WARNING: You are using pip version 21.2.4; however, version 25.0.1 is available.
You should consider upgrading via the '/Users/Grace/Downloads/3:10/web_app/.venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: plotly in /Users/Grace/Library/Python/3.9/lib/python/site-packages (6.0.0)
Requirement already satisfied: narwhals>=1.15.1 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from plotly) (1.30.0)
Requirement already satisfied: packaging in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from plotly) (24.2)
WARNING: You are using pip version 21.2.4; however, version 25.0.1 is available.
You should consider upgrading via the '/Users/Grace/Downloads/3:10/web_app/.venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/Grace/Library/Python/3.9/lib/python/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.22.4 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /Users/Grace/Library/Python/3.9/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
WARNING: You are using pip version 21.2.4; however, version 25.0.1 is available.
You should consider upgrading via the '/Users/Grace/Downloads/3:10/web_app/.venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [24]:
import pandas as pd

In [25]:
vehicle_df = pd.read_csv('/Users/Grace/Downloads/3:10/web_app/.venv/vehicles_us.csv')

In [26]:
vehicle_df.head(20)

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
0,9400,2011.0,bmw x5,good,6.0,gas,145000.0,automatic,SUV,NaN,1.0,2018-06-23,19
1,25500,NaN,ford f-150,good,6.0,gas,88705.0,automatic,pickup,white,1.0,2018-10-19,50
2,5500,2013.0,hyundai sonata,like new,4.0,gas,110000.0,automatic,sedan,red,NaN,2019-02-07,79
3,1500,2003.0,ford f-150,fair,8.0,gas,NaN,automatic,pickup,NaN,NaN,2019-03-22,9
4,14900,2017.0,chrysler 200,excellent,4.0,gas,80903.0,automatic,sedan,black,NaN,2019-04-02,28
5,14990,2014.0,chrysler 300,excellent,6.0,gas,57954.0,automatic,sedan,black,1.0,2018-06-20,15
6,12990,2015.0,toyota camry,excellent,4.0,gas,79212.0,automatic,sedan,white,NaN,2018-12-27,73
7,15990,2013.0,honda pilot,excellent,6.0,gas,109473.0,automatic,SUV,black,1.0,2019-01-07,68
8,11500,2012.0,kia sorento,excellent,4.0,gas,104174.0,automatic,SUV,NaN,1.0,2018-07-16,19
9,9200,2008.0,honda pilot,excellent,NaN,gas,147191.0,automatic,SUV,blue,1.0,2019-02-15,17
10,19500,2011.0,chevrolet silverado 1500,excellent,8.0,gas,128413.0,automatic,pickup,black,1.0,2018-09-17,38
11,8990,2012.0,honda accord,excellent,4.0,gas,111142.0,automatic,sedan,grey,NaN,2019-03-28,29
12,18990,2012.0,ram 1500,excellent,8.0,gas,140742.0,automatic,pickup,NaN,1.0,2019-04-02,37
13,16500,2018.0,hyundai sonata,excellent,4.0,gas,22104.0,automatic,sedan,silver,NaN,2019-01-14,29
14,12990,2009.0,gmc yukon,excellent,8.0,gas,132285.0,automatic,SUV,black,1.0,2019-01-31,24
15,17990,2013.0,ram 1500,excellent,8.0,gas,NaN,automatic,pickup,red,1.0,2018-05-15,111
16,14990,2010.0,ram 1500,excellent,8.0,gas,130725.0,automatic,pickup,red,1.0,2018-12-30,13
17,13990,2014.0,jeep cherokee,excellent,6.0,gas,100669.0,automatic,SUV,red,1.0,2018-08-16,25
18,12500,2013.0,chevrolet traverse,excellent,6.0,gas,128325.0,automatic,SUV,white,1.0,2019-04-09,13
19,13990,2018.0,hyundai elantra,excellent,4.0,gas,31932.0,automatic,sedan,red,NaN,2018-08-25,27

In [27]:
vehicle_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  int64
 1   model_year    47906 non-null  float64
 2   model         51525 non-null  object
 3   condition     51525 non-null  object
 4   cylinders     46265 non-null  float64
 5   fuel          51525 non-null  object
 6   odometer      43633 non-null  float64
 7   transmission  51525 non-null  object
 8   type          51525 non-null  object
 9   paint_color   42258 non-null  object
 10  is_4wd        25572 non-null  float64
 11  date_posted   51525 non-null  object
 12  days_listed   51525 non-null  int64
dtypes: float64(4), int64(2), object(7)
memory usage: 5.1+ MB

In [28]:
vehicle_df['is_4wd'] = vehicle_df['is_4wd'].astype('bool')

In [29]:
vehicle_df.isna().sum()

price              0
model_year      3619
model              0
condition          0
cylinders       5260
fuel               0
odometer        7892
transmission       0
type               0
paint_color     9267
is_4wd             0
date_posted        0
days_listed        0
dtype: int64

In [30]:
vehicle_df.dropna(inplace=True)

In [31]:
vehicle_df.duplicated().sum()

np.int64(0)

In [32]:
vehicle_df['model_year'] = vehicle_df['model_year'].astype(int)

In [33]:
vehicle_df['odometer'] = vehicle_df['odometer'].astype(int)

In [34]:
vehicle_df['date_posted'] = pd.to_datetime(vehicle_df['date_posted'])

In [35]:
vehicle_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29916 entries, 2 to 51523
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         29916 non-null  int64
 1   model_year    29916 non-null  int64
 2   model         29916 non-null  object
 3   condition     29916 non-null  object
 4   cylinders     29916 non-null  float64
 5   fuel          29916 non-null  object
 6   odometer      29916 non-null  int64
 7   transmission  29916 non-null  object
 8   type          29916 non-null  object
 9   paint_color   29916 non-null  object
 10  is_4wd        29916 non-null  bool
 11  date_posted   29916 non-null  datetime64[ns]
 12  days_listed   29916 non-null  int64
dtypes: bool(1), datetime64[ns](1), float64(1), int64(4), object(6)
memory usage: 3.0+ MB

In [36]:
vehicle_df.sample(20)

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
3968,13250,2013,ford f-250,excellent,8.0,gas,162000,automatic,pickup,red,True,2018-06-24,54
39230,4999,2007,volkswagen jetta,like new,5.0,gas,116000,automatic,sedan,black,True,2018-09-05,69
6791,32500,2018,chevrolet silverado,new,8.0,gas,3396,automatic,pickup,silver,True,2018-10-09,31
45461,18200,2013,dodge charger,excellent,8.0,gas,78812,automatic,sedan,silver,True,2019-03-18,21
9966,5795,2012,subaru impreza,excellent,4.0,gas,212000,manual,hatchback,black,True,2018-05-29,12
16033,5700,2007,subaru forester,good,4.0,gas,134000,automatic,wagon,green,True,2018-06-04,41
39643,5700,2013,nissan altima,good,6.0,gas,131522,automatic,sedan,silver,True,2018-08-05,14
6870,2700,2005,ram 1500,salvage,8.0,gas,221184,automatic,pickup,black,True,2018-05-15,34
41829,15000,2006,ford f-150,good,8.0,gas,127000,automatic,truck,red,True,2019-03-07,25
32830,1500,2005,volkswagen passat,fair,6.0,gas,195000,automatic,hatchback,black,True,2018-10-16,84
39724,13995,2008,chevrolet silverado 1500,excellent,8.0,gas,93300,automatic,truck,grey,True,2018-11-15,53
12398,10995,2012,honda accord,excellent,4.0,gas,68205,automatic,sedan,black,True,2018-06-06,52
44110,10400,2007,cadillac escalade,good,8.0,gas,113015,automatic,SUV,white,True,2018-11-25,50
24360,23995,2012,jeep wrangler,like new,6.0,gas,56167,automatic,SUV,silver,True,2018-05-08,20
19525,9500,2014,chevrolet cruze,like new,4.0,gas,43000,automatic,sedan,white,True,2019-03-03,109
51349,9499,2015,nissan altima,excellent,4.0,gas,91870,automatic,sedan,brown,True,2019-03-22,16
13682,8900,2013,chevrolet equinox,good,4.0,gas,120456,automatic,wagon,white,True,2019-01-12,28
42772,14888,2015,ford mustang,excellent,6.0,gas,71344,automatic,convertible,grey,True,2019-04-19,66
19394,6995,2002,ford f-150,good,6.0,gas,137428,automatic,truck,white,True,2018-12-01,43
28735,28000,2017,jeep wrangler unlimited,like new,6.0,gas,18300,automatic,SUV,black,True,2018-06-28,32

In [38]:
import plotly.express as px
import streamlit as st

In [42]:
st.header('Price Distribution') 
st.write('The price distribution of the vehicles is shown below.')
fig=px.histogram(vehicle_df, x='price', title='Price Distribution')
st.plotly_chart(fig)

2025-03-11 10:57:13.693 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:57:13.694 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:57:13.696 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:57:13.697 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:57:13.698 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:57:13.699 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:57:13.740 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:57:13.741 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:57:13.742 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:57:13.742 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [43]:
st.header('Vehicle model year vs price')
st.write('The relationship between vehicle model year and price is shown below.')
fig=px.scatter(vehicle_df, x='model_year', y='price', title='Vehicle model year vs price')
st.plotly_chart(fig)

2025-03-11 10:58:33.349 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:58:33.353 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:58:33.354 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:58:33.355 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:58:33.356 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:58:33.357 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:58:33.524 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:58:33.529 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:58:33.534 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:58:33.539 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [ ]:
st.header('Vehicle manufacturer vs price')
st.write('The relationship between vehicle manufacturer and price is shown below.')
manufacturer = vehicle_df['model'].s
fig=px.bar(vehicle_df, x='manufacturer', y='price', title='Vehicle manufacturer vs price')
st.plotly_chart(fig)

2025-03-11 10:59:11.932 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:59:11.933 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:59:11.934 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:59:11.934 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:59:11.936 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-11 10:59:11.937 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of ['price', 'model_year', 'model', 'condition', 'cylinders', 'fuel', 'odometer', 'transmission', 'type', 'paint_color', 'is_4wd', 'date_posted', 'days_listed'] but received: manufacturer